# Generated by Django 5.1.3 on 2024-11-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingApp', '0002_purchase_purchase_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
