# Generated by Django 5.1.3 on 2025-01-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0002_alter_denomination_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_id',
            field=models.CharField(blank=True, max_length=3, unique=True),
        ),
    ]
