# Generated by Django 5.1.3 on 2025-01-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0003_alter_purchase_purchase_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='balance_due',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='net_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='paid_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_price_without_tax',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_tax',
            field=models.FloatField(default=0),
        ),
    ]
